### ISSUE TITLE
Order of quotas and questions cannot be changed

### ISSUE THREAD

**Issue by jviitamo** [athenekilta/ilmomasiina#129]
When creating an event, there is a bug where you cannot change the initial order of given quotas and questions. When trying to change the order it comes back to the original after saving changes. Steps to recreate bug:

1. Create mockup data with `npm run create-fake-data`
2. Go to admin panel `http://localhost:3000/admin`
3. Open Columbia road - excu and change the order of the two quotas
4. Save changed data and see that the original order is back

**Comment by Sonlis** [comment]
I wonder if this is easily possible. From what I checked, the quota id is the primary key in the quota table, and same for question id. There are no other fields that could be checked to sort questions / quota in the admin page, do we want to create one ?
Current quota table: 
```
| id | title              | size | createdAt           | updatedAt           | deletedAt           | eventId | ```
Possible solution:
```
| id | title              | size | createdAt           | updatedAt           | deletedAt           | eventId | sortId|``` 
Same for question table.

**Comment by jviitamo** [comment]
I think we should implement your description and try to make the draggable handle change the sortId and then use sortId in events component to sort questions and quotas.
